name: Validate Documentation Links
on:
  pull_request:
    branches: [ master ]
    paths:
      - '**.md'
  push:
    branches: [ master ]
    paths:
      - '**.md'

jobs:
  validate-docs:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
      
      - name: Check for broken links
        run: |
          find . -name "*.md" -exec markdown-link-check {} \; 